### ISSUE TITLE
Add JWT validation on offers and publications api

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade#17]
As a cacaotrade admin i would like to restrict the access to the api to only registered users.  For this we should issue a JWT on the auth controller that should be appended to the header of every request done to the publications and offers api.  The logic to issue a token and validate it are already done on the authcontroller.  Please feel free to contact me if you need help with anything.

**Comment by BrandonArmand** [comment]
I'll take this for you. Easy stuff.

**Comment by BrandonArmand** [comment]
#18

**Comment by cacaotrade** [comment]
Everything looks good but could you please also validate the token for the post actions on offers and publications?

**Comment by jhidalgoesp** [comment]
Solved on #18
