### ISSUE TITLE
Express boilerplate

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade#2]
We realize we will start the development of cacaotrade from scratch for this i would like to update the repository with Express.js boilerplate including routes, controllers, models... etc

**Comment by jhidalgoesp** [comment]
Please assign this to me

**Comment by grovertb** [comment]
Can I work on this? :)

**Comment by jhidalgoesp** [comment]
I just opened a pull request for this issue.

**Comment by cacaotrade** [comment]
I will review this as soon as possible, thank you very much!

**Comment by praveen-me** [comment]
I would also consider you to use https://github.com/praveen-me/reenode.
This will create a production-ready boilerplate of node-react for you.

**Comment by cacaotrade** [comment]
Thanks, i will analize it moving forward!
