### ISSUE TITLE
Add Travis integration

### ISSUE THREAD

**Issue by jhidalgoesp** [cacaotrade/cacaotrade#20]
As a cacaotrade developer i would like to make sure the pull request made by me and other developers have no syntax errors.  For this i would like basic Travis CI integration to be made.

**Comment by Tomekmularczyk** [comment]
for this it would be best to have something like eslint, right? or do you have a better idea of how to check it?

**Comment by jhidalgoesp** [comment]
Yeah, i was planning on adding that on a different issue but it is probably the best to add it here.

**Comment by Tomekmularczyk** [comment]
@jhidalgoesp how about the standard eslint config for now? we can set up a minimum configuration and extend it later.

**Comment by jhidalgoesp** [comment]
Sounds good, let me know if you are going to be working on this.

**Comment by Tomekmularczyk** [comment]
@jhidalgoesp yup I will take care of it today 👍

**Comment by jhidalgoesp** [comment]
Solved on #22.
