### ISSUE TITLE
Add User model and crud actions 

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade#4]
As a cacaotrade user i would like to be able to store Users Mongo database, for this i would need an User model to be created with the following info: 

-   firstName
-   lastname
-   email
-   password
-   phone
-   status

These model should have the basic crud actions exposed via an API with validations using express validator,  the password must be stored as an encrypted string.

**Comment by cacaotrade** [comment]
@jhidalgoesp please let me know if you can help me with this.

**Comment by jhidalgoesp** [comment]
Sure i will.

**Comment by jhidalgoesp** [comment]
I just opened a pull request for this. Let me know if you need anything.

**Comment by cacaotrade** [comment]
Solved on #10 Thanks @jhidalgoesp
