### ISSUE TITLE
Add Supply model and crud actions

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade#5]
As a cacaotrade manager i would like to be able to store information about the cacao supply the users would create for this i would need a Publication model to be created with the following info:

- Message
- Type
- Geolocation Ej: UK, US, EC, CO, DE, BR
- Weight on lb(should be just weight on the db)
- Price per lb(should be just price on the db)
- User Id
- is_active (boolean)
- Created at
- Updated at
- Deleted at

These model should have the basic crud actions exposed via an API with validations using express-validator.

**Comment by wandersonpsantos** [comment]
dibs

**Comment by cacaotrade** [comment]
Pleas guide yourself with how the User implementation was done. Thanks for your help.

**Comment by cacaotrade** [comment]
This was solved on #12
