### ISSUE TITLE
Add JWT Logic

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade#6]
As a cacaotrade manager, i would like to add Security to the project.  For this i would like to: 

- add a /login endpoint to an AuthRoute file
- add a /logout endpoint
- add jwt tokens issuing logic on an AuthController
- add authentication middleware 

Keep in mind these would be done using the User model currently being developed,  it will be done using the email and password field.

**Comment by praveen-me** [comment]
Hi @cacaotrade, 
I would like to work on this issue.

**Comment by jhidalgoesp** [comment]
Hi i will be working on this issue

**Comment by cacaotrade** [comment]
@praveen-me Thanks, please let me know if you have any doubts.

**Comment by jhidalgoesp** [comment]
Just added a pull request for this

**Comment by cacaotrade** [comment]
Will review it asap.

**Comment by cacaotrade** [comment]
This was solved on #13. Thanks everyone for their help
